<?php
 
return [
    "hash" => env("INTRANET_OLD_WEBSERVICE_HASH", "INTRANET_OLD_WEBSERVICE_HASH"),
    "webservice_url_production" => env("INTRANET_OLD_WEBSERVICE_PRODUCTION_URL", "INTRANET_OLD_WEBSERVICE_PRODUCTION_URL"),
    "webservice_url_develoment" => env("INTRANET_OLD_WEBSERVICE_DEVELOPMENT_URL", "INTRANET_OLD_WEBSERVICE_DEVELOPMENT_URL")

];
 